Intra_nyt_default_template/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Intra_nyt_default_template.Models;
using Intra_nyt.Interface;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Hosting;

namespace Intra_nyt_default_template.Controllers
{
    public class HomeController : Controller
    {
        public readonly Intra_nytContext _context;
        public readonly IAuthen _Authen;
        public readonly IHostingEnvironment _env;
        public HomeController(Intra_nytContext context,IAuthen authen,IHostingEnvironment env)
        {
            _context = context;
            _Authen = authen;
            _env = env;
        }
        public async Task<IActionResult> Index_intra(string frompage) {
            var data = _context.nyt_News
                     .Where(n => n.status == "Main content")
                     .OrderByDescending(n => n.Id)
                     .Take(1);
            ViewBag.dataimg = data.ToList();

            var datanormal = _context.nyt_News
                .OrderByDescending(n => n.Id)
                .Take(6);
            ViewBag.datanormal = datanormal.ToList();
            if (frompage != null)
            {
                String Id = await _Authen.sentToken("emp_Id");
                String emp_name = await _Authen.sentToken("emp_name");
                String emp_sname = await _Authen.sentToken("emp_sname");
                if ((Id == "") || (emp_name == "") || (emp_sname == ""))
                {
                    return View();
                }
                else
                {
                    var UserRole = _context.authori
                              .Where(e => e.emp_Id.Trim() == Id && e.project_name == "news")
                              .ToList();

                    var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name,emp_name+" "+emp_sname),
                new Claim("employeeId",Id)
            };
                    //add userRole
                    foreach (var item in UserRole)
                    {
                        claims.Add(new Claim(ClaimTypes.Role, item.autho));
                    }

                    ClaimsIdentity userIdentity = new ClaimsIdentity(claims, "LvCookie");
                    ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);

                    //await _httpContextAccessor.HttpContext.SignInAsync(principal);
                    await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                         principal,
                      new AuthenticationProperties
                      {
                          ExpiresUtc = DateTime.UtcNow.AddHours(1),
                          IsPersistent = false,
                          AllowRefresh = false
                      });
                    return RedirectToAction("Index_intra", "Home");
                }
            }

            return View();
        }
        //[Route("/{fromlogin}")]
        public async Task<IActionResult> Index(String frompage)
        {
           // await HttpContext.SignOutAsync();
            var data = _context.nyt_News
                      .Where(n => n.status == "Main content")
                      .OrderByDescending(n => n.Id)
                      .Take(3);
            ViewBag.dataimg = data.ToList();
            
            var datanormal = _context.nyt_News
                .OrderByDescending(n => n.Id)
                .Take(6);
            ViewBag.datanormal = datanormal.ToList();
            if(frompage != null)
            {
                String Id = await _Authen.sentToken("emp_Id");
                String emp_name = await _Authen.sentToken("emp_name");
                String emp_sname = await _Authen.sentToken("emp_sname");
                if ((Id == "") || (emp_name == "") || (emp_sname == ""))
                {
                    return View();
                }
                else
                {
                    var UserRole = _context.authori
                              .Where(e => e.emp_Id.Trim() == Id && e.project_name == "news")
                              .ToList();

                    var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name,emp_name+" "+emp_sname),
                new Claim("employeeId",Id)
            };
                    //add userRole
                    foreach (var item in UserRole)
                    {
                        claims.Add(new Claim(ClaimTypes.Role, item.autho));
                    }

                    ClaimsIdentity userIdentity = new ClaimsIdentity(claims, "LvCookie");
                    ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);

                    //await _httpContextAccessor.HttpContext.SignInAsync(principal);
                    await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                         principal,
                      new AuthenticationProperties
                      {
                          ExpiresUtc = DateTime.UtcNow.AddHours(1),
                          IsPersistent = false,
                          AllowRefresh = false
                      });
                    return RedirectToAction("Index", "Home");
                }
            }

            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }
        //[Route("edit/{name}")]
        public IActionResult Contact(String name)
        {
            ViewData["Message"] = "Your contact page."+name;

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Intra_nyt_default_template/Controllers/nyt_NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Intra_nyt_default_template.Models;
using nyt_Netcore.Models;
using Intra_nyt.Interface;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using ReflectionIT.Mvc.Paging;
using Microsoft.IdentityModel.Tokens;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Routing;

namespace Intra_nyt_default_template.Controllers
{
    public class emp
    {
        string emp_name { get; set; }
    }
    public class nyt_NewsController : Controller
    {
        private readonly Intra_nytContext _context;
        private readonly IsaveFile _IsaveFile;
        private readonly IAuthen _Authen;
        public String _name = "";
       
        public nyt_NewsController(Intra_nytContext context, IsaveFile IsaveFile, IAuthen authen)
        {
            _context = context;
            _IsaveFile = IsaveFile;
            _Authen = authen;
        }
        public async Task<IActionResult> Index(String status,String dateFrom,String dateTo,int page = 1)
        {

            var news = from n in _context.nyt_News
                       select n;


            if (!string.IsNullOrEmpty(status))
            {
                news = news.Where(s => s.status.Contains(status));
            }

            if (!string.IsNullOrEmpty(dateFrom) && !string.IsNullOrEmpty(dateTo))
            {
                String[] fromArr = dateFrom.Split('/');
                String[] toArr = dateTo.Split('/');
                String fromDay = fromArr[2] + "-" + fromArr[1] + "-" + fromArr[0];
                String toDay = toArr[2] + "-" + toArr[1] + "-" + toArr[0];
                news = news.Where(s => s.createdate >= DateTime.Parse(fromDay) && s.createdate <= DateTime.Parse(toDay));
            }


            news = news.OrderBy(n => n.status);

            var model = await PagingList.CreateAsync(
                                   news, 1, page, "status", "status");

            model.RouteValue = new RouteValueDictionary
            {
                {"dateFrom",dateFrom },
                {"dateTo",dateTo },
                {"status",status }
            };

            ViewBag.status = status;
           
            return View(model);
            //return View(await _context.nyt_News.ToListAsync());
        }
        public async Task<IActionResult> index_intra(String status, String dateFrom, String dateTo, int page = 1)
        {
            var news = from n in _context.nyt_News
                       select n;
            if (!string.IsNullOrEmpty(status))
            {
                news = news.Where(s => s.status.Contains(status));
            }

            if (!string.IsNullOrEmpty(dateFrom) && !string.IsNullOrEmpty(dateTo))
            {
                String[] fromArr = dateFrom.Split('/');
                String[] toArr = dateTo.Split('/');
                String fromDay = fromArr[2] + "-" + fromArr[1] + "-" + fromArr[0];
                String toDay = toArr[2] + "-" + toArr[1] + "-" + toArr[0];
                news = news.Where(s => s.createdate >= DateTime.Parse(fromDay) && s.createdate <= DateTime.Parse(toDay));
            }


            news = news.OrderBy(n => n.status);

            var model = await PagingList.CreateAsync(
                                   news, 1, page, "status", "status");

            model.RouteValue = new RouteValueDictionary
            {
                {"dateFrom",dateFrom },
                {"dateTo",dateTo },
                {"status",status }
            };

            ViewBag.status = status;

            return View(model);
        }

        // GET: nyt_News/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            //getAuthen();
            if (id == null)
            {
                return NotFound();
            }

            var nyt_News = await _context.nyt_News
                .FirstOrDefaultAsync(m => m.Id == id);
            if (nyt_News == null)
            {
                return NotFound();
            }

            var imgDetail = _context.gallery_News
                           .Where(n => n.ref_Id == id.ToString())
                           .OrderBy(n => n.Id);
            ViewBag.gallery = imgDetail.ToList();
            return View(nyt_News);
        }

        // GET: nyt_News/Create
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create()
        {

            IQueryable<string> depQu = from m in _context.department
                        orderby m.dep_name
                        select m.dep_name;
            var news = new nyt_News
            {
                deplist = new SelectList(await depQu.Distinct().ToListAsync()),
                //employees = await emp.ToListAsync()
            };
            return View(news);
        }

        // POST: nyt_News/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public async Task<IActionResult> Create(nyt_News nyt_News,List<IFormFile> img_hidden0,gallery_News gallery_News,IFormFile file_hidden0)
        {
            if (ModelState.IsValid)
            {
                for (int i = 0; i < img_hidden0.Count; i++)
                {
                    String path = "";
                    String file = "";
                    if (i == 0)
                    {
                        if (img_hidden0[0] != null)
                        {
                            path = "/images/News/";
                            file = await _IsaveFile.save(img_hidden0[0], path);
                            nyt_News.img = file;
                            nyt_News.attachfile = await _IsaveFile.save(file_hidden0, "/attachfile/News/");
                            nyt_News.createdate = DateTime.Now;
                            _context.Add(nyt_News);
                            await _context.SaveChangesAsync();
                        }
                    }
                    if (img_hidden0[i] != null)
                    {
                        if (img_hidden0[i] != null)
                        {
                            path = "/images/News/";
                            file = await _IsaveFile.save(img_hidden0[i], path);
                            var gall = new gallery_News {
                                ref_Id = nyt_News.Id.ToString(),
                                type = "Image",
                                path=file,
                            };
                            _context.gallery_News.Add(gall);
                        }
                    }

                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(nyt_News);
        }

        // GET: nyt_News/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            //getAuthen();
            if (id == null)
            {
                return NotFound();
            }

            var nyt_News = await _context.nyt_News.FindAsync(id);
            if (nyt_News == null)
            {
                return NotFound();
            }
            return View(nyt_News);
        }

        // POST: nyt_News/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,title,detail,img,attachfile,createdate,status,department")] nyt_News nyt_News)
        {
            if (id != nyt_News.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(nyt_News);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!nyt_NewsExists(nyt_News.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(nyt_News);
        }

        // GET: nyt_News/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nyt_News = await _context.nyt_News
                .FirstOrDefaultAsync(m => m.Id == id);
            if (nyt_News == null)
            {
                return NotFound();
            }

            return View(nyt_News);
        }

        // POST: nyt_News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var nyt_News = await _context.nyt_News.FindAsync(id);
            _context.nyt_News.Remove(nyt_News);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool nyt_NewsExists(int id)
        {
            return _context.nyt_News.Any(e => e.Id == id);
        }
    }
}

Intra_nyt_default_template/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Intra_nyt_default_template/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Intra_nyt_default_template/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row sec">
    <div class="col-md-9" style="margin-left:-10px">
        <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">

            <div class="carousel-outer">
                <div class="carousel-inner" role="listbox">
                    <ol class="carousel-indicators">
                        @for (int i = 0; i < ViewBag.dataimg.Count; i++)
                        {
                            String cStr = "";
                            if (i < 1)
                            {
                                cStr = "active";
                            }
                            else
                            {
                                cStr = "";
                            }
                            <li data-target="#myCarousel" data-slide-to="@i" class="@cStr"></li>
                        }
                        @*<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                            <li data-target="#myCarousel" data-slide-to="1"></li>
                            <li data-target="#myCarousel" data-slide-to="2"></li>*@
                    </ol>
                    @for (int i = 0; i < ViewBag.dataimg.Count; i++)
                    {
                        String cDiv = "";
                        String slide = "";
                        String slideDetail = "";
                        slide = "slide" + i.ToString();
                        slideDetail = "slideDetail" + i.ToString();
                        if (i < 1)
                        {
                            cDiv = "item active";

                        }
                        else
                        {
                            cDiv = "item";
                        }
                        <div id="@slide" class="@cDiv">
                            <a asp-controller="nyt_News" asp-action="Details" asp-route-id="@ViewBag.dataimg[i].Id">
                                @{ String path = "http://192.168.2.11/information" + ViewBag.dataimg[i].img;}
                                <img src="@path" alt="ASP.NET" class="" style="width:1500px;height:350px" />
                                <div class="carousel-caption" role="option">

                                    <p id="@slideDetail" style="display:none">
                                        @ViewBag.dataimg[i].detail

                                    </p>
                                </div>
                            </a>

                        </div>
                    }


                </div>
                <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>


        </div>

    </div>
    <div class="col-md-3">
        <div style="margin-top:-20px">
            <div class="title-line">
                <span>
                    ข่าวใหม่
                </span>
            </div>
            @*<h3 id="title-detail" class="my-3">Project Description</h3>*@
            @*<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>*@
            <p id="cDetail"></p>
        </div>


    </div>
</div>

<div class="">
    <div class="title-line">
        <span>
            ประชาสัมพันธ์
        </span>
    </div>

    <div class="row">
        @*<div class="col-md-3">
                <h2>Application uses</h2>
                <ul>
                    <li>Sample pages using ASP.NET Core MVC</li>
                    <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
                </ul>
            </div>*@
        @foreach (var item in ViewBag.datanormal)
        {
            <a asp-controller="nyt_News" asp-action="Details" asp-route-id="@item.Id">
                <div class="col-md-4" style="margin-top:3px">
                    <div class="card">
                        @{ String path = "http://192.168.2.11/information" + item.img;}
                        <img src="@path" style="width:357px" class="zoom" />
                        <div class="card-body">
                            <p class="card-text">

                                @item.detail.ToString().Substring(0, 100)..
                            </p>
                            <hr />
                            @item.createdate
                        </div>
                    </div>
                </div>
            </a>

        }

    </div>
</div>
@section Scripts{

    <script>
        $(document).ready(function () {
            $("#home").addClass("active");
            var s = document.getElementById("slideDetail0").innerText;
            if (s.length > 240) {
                s = s.substring(0, 240);
            }
            $("#cDetail").text(s);
            // alert(s);
            $('#myCarousel').on('slid.bs.carousel', function () {
                for (i = 0; i <= 3; i++) {

                    if ($("#slide" + i).hasClass("active")) {

                        s = document.getElementById("slideDetail" + i).innerText;
                        // alert(s.length);
                        if (s.length > 240) {
                            s = s.substring(0, 240);
                        }
                        $("#cDetail").html(s);
                    }
                }

            })

        });
    </script>
    <script type="text/javascript">
        function addDetail(title, detail) {
            $("#cDetail").html(title);
        }
    </script>
}